### ISSUE TITLE
win/ubuntu推断结果不一致

### ISSUE THREAD

**Issue by 4nthon** [minivision-ai/Silent-Face-Anti-Spoofing#17]
image_F1.jpg在win下0.73FakeFace，但是在ubuntu18.04下是0.55RealFace，同样的电脑双系统，同样的环境包版本，为什么会推断出不一致的结果？

**Comment by zhuyingSeu** [comment]
可能是系统不一样，位数不一样。

**Comment by 4nthon** [comment]
感谢您的回复

**Comment by 4nthon** [comment]
您好我发现了一个新问题。当Torch版本为CPU版本的时候，识别准确度略微下降，同时RetinaFace无法返回有效bbox坐标，GPU下完全ok。 @zhuyingSeu

**Comment by ligaoyuan-potato** [comment]
你在电脑上跑通过了吗？我跑的加载模型会报错

  File "D:\project\alive_detect\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 32, in __init__
    self.detector = cv2.dnn.readNetFromCaffe(deploy, caffemodel)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: ./resources/detection_model/deploy.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie'

**Comment by 4nthon** [comment]
> 你在电脑上跑通过了吗？我跑的加载模型会报错
> 
> File "D:\project\alive_detect\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 32, in **init**
> self.detector = cv2.dnn.readNetFromCaffe(deploy, caffemodel)
> cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: ./resources/detection_model/deploy.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie'

你的问题是OpenCV版本过低，请尝试OpenCV4.2.0+

**Comment by ligaoyuan-potato** [comment]
谢谢！


另外，请问下你们活体这个有服务端的产品吗？我们公司打算私有化部署一套


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minivision-ai/Silent-Face-Anti-Spoofing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 上午8:54
收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;;
抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17)





  
你在电脑上跑通过了吗？我跑的加载模型会报错
 
File "D:\project\alive_detect\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 32, in init
 self.detector = cv2.dnn.readNetFromCaffe(deploy, caffemodel)
 cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: ./resources/detection_model/deploy.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie'
  
你的问题是OpenCV版本过低，请尝试OpenCV4.2.0+

**Comment by 4nthon** [comment]
> 谢谢！ 另外，请问下你们活体这个有服务端的产品吗？我们公司打算私有化部署一套
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minivision-ai/Silent-Face-Anti-Spoofing" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 上午8:54 收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;; 抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17) 你在电脑上跑通过了吗？我跑的加载模型会报错 File "D:\project\alive_detect\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 32, in init self.detector = cv2.dnn.readNetFromCaffe(deploy, caffemodel) cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: ./resources/detection_model/deploy.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie' 你的问题是OpenCV版本过低，请尝试OpenCV4.2.0+ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，我不是作者，上面都是我提的问题。。。。

**Comment by ligaoyuan-potato** [comment]
哦哦，不好意思，你有跑通过吗？效果如何呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minivision-ai/Silent-Face-Anti-Spoofing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 上午8:57
收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;;
抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17)





  
谢谢！ 另外，请问下你们活体这个有服务端的产品吗？我们公司打算私有化部署一套
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minivision-ai/Silent-Face-Anti-Spoofing" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 上午8:54 收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;; 抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17) 你在电脑上跑通过了吗？我跑的加载模型会报错 File "D:\project\alive_detect\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 32, in init self.detector = cv2.dnn.readNetFromCaffe(deploy, caffemodel) cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: ./resources/detection_model/deploy.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie' 你的问题是OpenCV版本过低，请尝试OpenCV4.2.0+ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你好，我不是作者，上面都是我提的问题。。。。

**Comment by 4nthon** [comment]
> 哦哦，不好意思，你有跑通过吗？效果如何呢？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minivision-ai/Silent-Face-Anti-Spoofing" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 上午8:57 收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;; 抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17) 谢谢！ 另外，请问下你们活体这个有服务端的产品吗？我们公司打算私有化部署一套 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minivision-ai/Silent-Face-Anti-Spoofing" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 上午8:54 收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;; 抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17) 你在电脑上跑通过了吗？我跑的加载模型会报错 File "D:\project\alive_detect\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 32, in init self.detector = cv2.dnn.readNetFromCaffe(deploy, caffemodel) cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: ./resources/detection_model/deploy.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie' 你的问题是OpenCV版本过低，请尝试OpenCV4.2.0+ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，我不是作者，上面都是我提的问题。。。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

可以跑通啊 效果挺好的 就是他们开源那个97%的，Ubuntu下面有点问题，我现在也在考虑部署，你有什么好的建议吗

**Comment by ligaoyuan-potato** [comment]
我跑了好几模型了，感觉效果都不是很好，还是配合的那种靠谱些，可以加一下微信吗？
13720549350




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minivision-ai/Silent-Face-Anti-Spoofing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 上午9:01
收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;;
抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17)





  
哦哦，不好意思，你有跑通过吗？效果如何呢？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minivision-ai/Silent-Face-Anti-Spoofing" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 上午8:57 收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;; 抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17) 谢谢！ 另外，请问下你们活体这个有服务端的产品吗？我们公司打算私有化部署一套 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minivision-ai/Silent-Face-Anti-Spoofing" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 上午8:54 收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;; 抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17) 你在电脑上跑通过了吗？我跑的加载模型会报错 File "D:\project\alive_detect\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 32, in init self.detector = cv2.dnn.readNetFromCaffe(deploy, caffemodel) cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: ./resources/detection_model/deploy.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie' 你的问题是OpenCV版本过低，请尝试OpenCV4.2.0+ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，我不是作者，上面都是我提的问题。。。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可以跑通啊 效果挺好的 就是他们开源那个97%的，Ubuntu下面有点问题，我现在也在考虑部署，你有什么好的建议吗

**Comment by 4nthon** [comment]
> 我跑了好几模型了，感觉效果都不是很好，还是配合的那种靠谱些，可以加一下微信吗？ 13720549350
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minivision-ai/Silent-Face-Anti-Spoofing" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 上午9:01 收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;; 抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17) 哦哦，不好意思，你有跑通过吗？效果如何呢？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minivision-ai/Silent-Face-Anti-Spoofing" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 上午8:57 收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;; 抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17) 谢谢！ 另外，请问下你们活体这个有服务端的产品吗？我们公司打算私有化部署一套 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minivision-ai/Silent-Face-Anti-Spoofing" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月13日(星期四) 上午8:54 收件人:&nbsp;"minivision-ai/Silent-Face-Anti-Spoofing"<Silent-Face-Anti-Spoofing@noreply.github.com&gt;; 抄送:&nbsp;"li_gaoy"<li_gaoy@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [minivision-ai/Silent-Face-Anti-Spoofing] win/ubuntu推断结果不一致 (#17) 你在电脑上跑通过了吗？我跑的加载模型会报错 File "D:\project\alive_detect\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 32, in init self.detector = cv2.dnn.readNetFromCaffe(deploy, caffemodel) cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1151: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: ./resources/detection_model/deploy.prototxt in function 'cv::dnn::ReadNetParamsFromTextFileOrDie' 你的问题是OpenCV版本过低，请尝试OpenCV4.2.0+ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，我不是作者，上面都是我提的问题。。。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 可以跑通啊 效果挺好的 就是他们开源那个97%的，Ubuntu下面有点问题，我现在也在考虑部署，你有什么好的建议吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的
